"""Utilitaires pour les services de génération de diagrammes."""
import base64
import os
import re
import shlex
import subprocess

from constants import TEXT_FORMATS, MIME_TYPES
from utils import InputValidator


def redact_temp_paths(text: str, *paths: str) -> str:
    """
    Remplace les chemins de fichiers temporaires par leur simple nom de
    fichier, pour ne pas exposer l'arborescence du serveur au client.

    Args:
        text: Texte dans lequel effectuer le remplacement
        *paths: Chemins complets à rédiger

    Returns:
        str: Texte avec les chemins remplacés par leur basename
    """
    for path in paths:
        if path:
            text = text.replace(path, os.path.basename(path))
    return text


def has_fatal_error(stdout_txt: str, stderr_txt: str) -> bool:
    """
    Vérifie si la sortie contient une erreur fatale.

    Args:
        stdout_txt: Sortie standard
        stderr_txt: Sortie d'erreur

    Returns:
        bool: True si erreur fatale détectée
    """
    return ("error:" in (stdout_txt or "").lower()) or ("error:" in (stderr_txt or "").lower())


def parse_extra_args(extra_args: str, tool: str) -> list[str]:
    """
    Parse les arguments supplémentaires, en rejetant tout flag absent de
    l'allowlist du tool (EXTRA_ARGS_ALLOWED_FLAGS).

    Args:
        extra_args: Arguments supplémentaires en string
        tool: Clé dans EXTRA_ARGS_ALLOWED_FLAGS identifiant l'outil cible

    Returns:
        list[str]: Liste des arguments parsés

    Raises:
        ValueError: Si les arguments sont invalides ou contiennent un flag non autorisé
    """
    if not extra_args or not extra_args.strip():
        return []
    try:
        tokens = shlex.split(extra_args.strip())
    except ValueError:
        raise ValueError("Invalid extraArgs: could not parse the value (check for unmatched quotes).")

    bad_flag = InputValidator.find_disallowed_flag(tokens, tool)
    if bad_flag:
        raise ValueError(f"Extra arg flag '{bad_flag}' is not allowed.")

    return tokens


_SAFE_FORMAT_EXTENSIONS = {fmt: fmt for fmt in MIME_TYPES}


def get_safe_format_extension(output_format: str) -> str:
    """
    Look up output_format in a hardcoded allowlist and return the matching
    literal extension string.

    Args:
        output_format: Output format to check

    Returns:
        str: The same format string, sourced from a hardcoded mapping

    Raises:
        ValueError: If output_format is not in MIME_TYPES
    """
    try:
        return _SAFE_FORMAT_EXTENSIONS[output_format]
    except KeyError:
        raise ValueError(f"Unsupported output format: {output_format!r}")


def encode_content(content: bytes, output_format: str) -> str:
    """
    Encode le contenu en base64 ou UTF-8 selon le format.

    Args:
        content: Contenu à encoder
        output_format: Format de sortie

    Returns:
        str: Contenu encodé
    """
    if output_format in TEXT_FORMATS:
        return content.decode("utf-8")
    return base64.b64encode(content).decode("utf-8")


_GITHUB_ICONS_BASE = (
    "https://raw.githubusercontent.com/mingrammer/diagrams/refs/heads/master/"
)


def _local_path_to_github_url(path: str) -> str:
    """
    Convert a local diagrams-package icon path to its GitHub CDN URL.

    The .dot file generated by aws-cfn-diagrams references icons via local
    paths (site-packages/resources/...). Running `dot -Tsvg` on it preserves
    those local paths as-is, so this restores the GitHub URLs the browser
    needs to load the icons.
    """
    m = re.search(r'resources/.+', path)
    return _GITHUB_ICONS_BASE + m.group() if m else path


def dot_to_svg(dot_text: str) -> str | None:
    """
    Render DOT source to SVG via `dot -Tsvg`, then fix local icon paths into
    GitHub CDN URLs. dot embeds icons in the SVG as xlink:href pointing to
    the absolute local filesystem path used at generation time, which the
    browser can't resolve.

    Args:
        dot_text: DOT source text.

    Returns:
        str | None: The rendered SVG text, or None if the conversion failed.
    """
    try:
        result = subprocess.run(
            ["dot", "-Tsvg"],
            input=dot_text,
            capture_output=True,
            text=True,
            check=False
        )
        if result.returncode != 0 or not result.stdout:
            return None

        return re.sub(
            r'xlink:href="([^"]*resources/[^"]+)"',
            lambda m: f'xlink:href="{_local_path_to_github_url(m.group(1))}"',
            result.stdout,
        )
    except Exception:
        return None

